version: 2

defaults: &defaults
  working_directory: ~/envdoctor
  docker:
    - image: circleci/node:10

jobs:
  install-dependencies:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/envdoctor
      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v3-dependencies-
      - run:
          name: Install Dependencies
          command: |
            yarn install --frozen-lockfile
            yarn run bootstrap
      - save_cache:
          key: v3-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - packages/core/node_modules
            - packages/envdoctor-config-essentials/node_modules
            - packages/utils/node_modules
      - persist_to_workspace:
          root: .
          paths: .
  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/envdoctor
      - run: yarn run lint
  tests:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/envdoctor
      - restore_cache:
          keys:
            - v3-jest-cache-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v3-jest-cache-
      - run: yarn run test
      - save_cache:
          key: v3-jest-cache-{{ checksum "yarn.lock" }}
          paths:
            - .jestCache
      - persist_to_workspace:
          root: .
          paths: .
  tests-coverage:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/envdoctor
      - run: |
          yarn test -- --coverage
          bash <(curl -s https://codecov.io/bash)
      - store_artifacts:
          path: coverage
      - persist_to_workspace:
          root: .
          paths: .
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/envdoctor
      - run: yarn run build
      - persist_to_workspace:
          root: .
          paths: .
  deploy-website:
    <<: *defaults
    working_directory: ~/envdoctor/website
    environment:
      GIT_AUTHOR_NAME: Envdoctor
      GIT_AUTHOR_EMAIL: jukben+envdoctor@gmail.com
      GIT_COMMITTER_NAME: Envdoctor
      GIT_COMMITTER_EMAIL: jukben+envdoctor@gmail.com
    steps:
      - add_ssh_keys:
          fingerprints:
            - "0b:78:b8:97:f2:8d:ad:38:87:2d:d5:c2:38:63:14:29"
      - checkout
      - attach_workspace:
          at: ~/envdoctor
      - run: |
          yarn --frozen-lockfile 
          GIT_USER=jukben CURRENT_BRANCH=master USE_SSH=true yarn run publish-gh-pages

workflows:
  version: 2
  build:
    jobs:
      - install-dependencies
          branches:
              ignore:
                - gh-pages
      - lint:
          requires:
            - install-dependencies
      - build:
          requires:
            - install-dependencies
      - tests:
          requires:
            - install-dependencies
            - build
      - tests-coverage:
          requires:
            - tests
      - deploy-website:
          requires:
            - install-dependencies
          filters:
            branches:
              only: master
